spring:
  application:
    name: ticket-message-service
  data:
    mongodb:
      uri: mongodb://app_user:ticket_bd@localhost:27017/ticket_bd
      database: ticket_bd
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: werpipl15
  mail:
    host: smtp.yandex.com
    port: 465
    username: AnotherSc@yandex.ru
    password: cufzeqevxzjpwozi
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9292

