services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: no
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=werpipl15
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: no

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticket
    ports:
      - "5432:5432"
    restart: no
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "
      docker-entrypoint.sh postgres &
      sleep 10 &&
      psql -U root -d ticket -c \"CREATE ROLE admin WITH LOGIN PASSWORD 'admin';\" &&
      psql -U root -d ticket -c \"GRANT ALL PRIVILEGES ON DATABASE ticket TO admin;\" &&
      psql -U root -d ticket -c \"ALTER ROLE admin WITH SUPERUSER;\" &&
      wait
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    restart: no

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin    # Имя пользователя для админ-доступа
      MONGO_INITDB_ROOT_PASSWORD: password # Пароль для админ-доступа
    command: mongod --bind_ip_all
    volumes:
      - mongodb_data:/data/db              # Хранение данных на хосте
      - mongodb_config:/data/configdb      # Конфигурационные данные
      - ./init-scripts:/docker-entrypoint-initdb.d # Скрипты инициализации

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: no
    ports:
      - "8081:8081" # Порт для веб-интерфейса
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin    # Имя пользователя MongoDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: password # Пароль MongoDB
      ME_CONFIG_MONGODB_SERVER: mongodb         # Хост MongoDB (имя сервиса)
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin  # Явно указать базу аутентификации

volumes:
  postgres_data:
  mongodb_data:
  mongodb_config:

