spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  spring:
    jpa:
      properties:
        hibernate:
          jdbc:
            batch_size=1000:
logging:
  file:
    name: report_log.log
  level:
    org.springframework: error
server:
  port: 9393
