spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size=1000:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: werpipl15
logging:
  file:
    name: report_log.log
  level:
    org.springframework: error
server:
  port: 9393
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
queue:
  name:
    SendMailReport: MessageSendMailReport
path:
  report: /home/another/Project/developering/ticket-management-system/report/

